module.exports = {
    countries: [
        {country_pk: 1, code: 'AF', name: 'Afghanistan'},
        {country_pk: 2, code: 'AL', name: 'Albania'},
        {country_pk: 3, code: 'DZ', name: 'Algeria'},
        {country_pk: 4, code: 'AS', name: 'American Samoa'},
        {country_pk: 5, code: 'AD', name: 'Andorra'},
        {country_pk: 6, code: 'AO', name: 'Angola'},
        {country_pk: 7, code: 'AI', name: 'Anguilla'},
        {country_pk: 8, code: 'AQ', name: 'Antarctica'},
        {country_pk: 9, code: 'AG', name: 'Antigua And Barbuda'},
        {country_pk: 10, code: 'AR', name: 'Argentina'},
        {country_pk: 11, code: 'AM', name: 'Armenia'},
        {country_pk: 12, code: 'AW', name: 'Aruba'},
        {country_pk: 13, code: 'AU', name: 'Australia'},
        {country_pk: 14, code: 'AT', name: 'Austria'},
        {country_pk: 15, code: 'AZ', name: 'Azerbaijan'},
        {country_pk: 16, code: 'BS', name: 'Bahamas The'},
        {country_pk: 17, code: 'BH', name: 'Bahrain'},
        {country_pk: 18, code: 'BD', name: 'Bangladesh'},
        {country_pk: 19, code: 'BB', name: 'Barbados'},
        {country_pk: 20, code: 'BY', name: 'Belarus'},
        {country_pk: 21, code: 'BE', name: 'Belgium'},
        {country_pk: 22, code: 'BZ', name: 'Belize'},
        {country_pk: 23, code: 'BJ', name: 'Benin'},
        {country_pk: 24, code: 'BM', name: 'Bermuda'},
        {country_pk: 25, code: 'BT', name: 'Bhutan'},
        {country_pk: 26, code: 'BO', name: 'Bolivia'},
        {country_pk: 27, code: 'BA', name: 'Bosnia and Herzegovina'},
        {country_pk: 28, code: 'BW', name: 'Botswana'},
        {country_pk: 29, code: 'BV', name: 'Bouvet Island'},
        {country_pk: 30, code: 'BR', name: 'Brazil'},
        {country_pk: 31, code: 'IO', name: 'British Indian Ocean Territory'},
        {country_pk: 32, code: 'BN', name: 'Brunei'},
        {country_pk: 33, code: 'BG', name: 'Bulgaria'},
        {country_pk: 34, code: 'BF', name: 'Burkina Faso'},
        {country_pk: 35, code: 'BI', name: 'Burundi'},
        {country_pk: 36, code: 'KH', name: 'Cambodia'},
        {country_pk: 37, code: 'CM', name: 'Cameroon'},
        {country_pk: 38, code: 'CA', name: 'Canada'},
        {country_pk: 39, code: 'CV', name: 'Cape Verde'},
        {country_pk: 40, code: 'KY', name: 'Cayman Islands'},
        {country_pk: 41, code: 'CF', name: 'Central African Republic'},
        {country_pk: 42, code: 'TD', name: 'Chad'},
        {country_pk: 43, code: 'CL', name: 'Chile'},
        {country_pk: 44, code: 'CN', name: 'China'},
        {country_pk: 45, code: 'CX', name: 'Christmas Island'},
        {country_pk: 46, code: 'CC', name: 'Cocos (Keeling) Islands'},
        {country_pk: 47, code: 'CO', name: 'Colombia'},
        {country_pk: 48, code: 'KM', name: 'Comoros'},
        {country_pk: 49, code: 'CG', name: 'Congo'},
        {country_pk: 50, code: 'CD', name: 'Congo The Democratic Republic Of The'},
        {country_pk: 51, code: 'CK', name: 'Cook Islands'},
        {country_pk: 52, code: 'CR', name: 'Costa Rica'},
        {country_pk: 53, code: 'CI', name: 'Cote D\'\'Ivoire (Ivory Coast)'},
        {country_pk: 54, code: 'HR', name: 'Croatia (Hrvatska)'},
        {country_pk: 55, code: 'CU', name: 'Cuba'},
        {country_pk: 56, code: 'CY', name: 'Cyprus'},
        {country_pk: 57, code: 'CZ', name: 'Czech Republic'},
        {country_pk: 58, code: 'DK', name: 'Denmark'},
        {country_pk: 59, code: 'DJ', name: 'Djibouti'},
        {country_pk: 60, code: 'DM', name: 'Dominica'},
        {country_pk: 61, code: 'DO', name: 'Dominican Republic'},
        {country_pk: 62, code: 'TP', name: 'East Timor'},
        {country_pk: 63, code: 'EC', name: 'Ecuador'},
        {country_pk: 64, code: 'EG', name: 'Egypt'},
        {country_pk: 65, code: 'SV', name: 'El Salvador'},
        {country_pk: 66, code: 'GQ', name: 'Equatorial Guinea'},
        {country_pk: 67, code: 'ER', name: 'Eritrea'},
        {country_pk: 68, code: 'EE', name: 'Estonia'},
        {country_pk: 69, code: 'ET', name: 'Ethiopia'},
        {country_pk: 70, code: 'XA', name: 'External Territories of Australia'},
        {country_pk: 71, code: 'FK', name: 'Falkland Islands'},
        {country_pk: 72, code: 'FO', name: 'Faroe Islands'},
        {country_pk: 73, code: 'FJ', name: 'Fiji Islands'},
        {country_pk: 74, code: 'FI', name: 'Finland'},
        {country_pk: 75, code: 'FR', name: 'France'},
        {country_pk: 76, code: 'GF', name: 'French Guiana'},
        {country_pk: 77, code: 'PF', name: 'French Polynesia'},
        {country_pk: 78, code: 'TF', name: 'French Southern Territories'},
        {country_pk: 79, code: 'GA', name: 'Gabon'},
        {country_pk: 80, code: 'GM', name: 'Gambia The'},
        {country_pk: 81, code: 'GE', name: 'Georgia'},
        {country_pk: 82, code: 'DE', name: 'Germany'},
        {country_pk: 83, code: 'GH', name: 'Ghana'},
        {country_pk: 84, code: 'GI', name: 'Gibraltar'},
        {country_pk: 85, code: 'GR', name: 'Greece'},
        {country_pk: 86, code: 'GL', name: 'Greenland'},
        {country_pk: 87, code: 'GD', name: 'Grenada'},
        {country_pk: 88, code: 'GP', name: 'Guadeloupe'},
        {country_pk: 89, code: 'GU', name: 'Guam'},
        {country_pk: 90, code: 'GT', name: 'Guatemala'},
        {country_pk: 91, code: 'XU', name: 'Guernsey and Alderney'},
        {country_pk: 92, code: 'GN', name: 'Guinea'},
        {country_pk: 93, code: 'GW', name: 'Guinea-Bissau'},
        {country_pk: 94, code: 'GY', name: 'Guyana'},
        {country_pk: 95, code: 'HT', name: 'Haiti'},
        {country_pk: 96, code: 'HM', name: 'Heard and McDonald Islands'},
        {country_pk: 97, code: 'HN', name: 'Honduras'},
        {country_pk: 98, code: 'HK', name: 'Hong Kong S.A.R.'},
        {country_pk: 99, code: 'HU', name: 'Hungary'},
        {country_pk: 100, code: 'IS', name: 'Iceland'},
        {country_pk: 101, code: 'IN', name: 'India'},
        {country_pk: 102, code: 'ID', name: 'Indonesia'},
        {country_pk: 103, code: 'IR', name: 'Iran'},
        {country_pk: 104, code: 'IQ', name: 'Iraq'},
        {country_pk: 105, code: 'IE', name: 'Ireland'},
        {country_pk: 106, code: 'IL', name: 'Israel'},
        {country_pk: 107, code: 'IT', name: 'Italy'},
        {country_pk: 108, code: 'JM', name: 'Jamaica'},
        {country_pk: 109, code: 'JP', name: 'Japan'},
        {country_pk: 110, code: 'XJ', name: 'Jersey'},
        {country_pk: 111, code: 'JO', name: 'Jordan'},
        {country_pk: 112, code: 'KZ', name: 'Kazakhstan'},
        {country_pk: 113, code: 'KE', name: 'Kenya'},
        {country_pk: 114, code: 'KI', name: 'Kiribati'},
        {country_pk: 115, code: 'KP', name: 'Korea North'},
        {country_pk: 116, code: 'KR', name: 'Korea South'},
        {country_pk: 117, code: 'KW', name: 'Kuwait'},
        {country_pk: 118, code: 'KG', name: 'Kyrgyzstan'},
        {country_pk: 119, code: 'LA', name: 'Laos'},
        {country_pk: 120, code: 'LV', name: 'Latvia'},
        {country_pk: 121, code: 'LB', name: 'Lebanon'},
        {country_pk: 122, code: 'LS', name: 'Lesotho'},
        {country_pk: 123, code: 'LR', name: 'Liberia'},
        {country_pk: 124, code: 'LY', name: 'Libya'},
        {country_pk: 125, code: 'LI', name: 'Liechtenstein'},
        {country_pk: 126, code: 'LT', name: 'Lithuania'},
        {country_pk: 127, code: 'LU', name: 'Luxembourg'},
        {country_pk: 128, code: 'MO', name: 'Macau S.A.R.'},
        {country_pk: 129, code: 'MK', name: 'North Macedonia'},
        {country_pk: 130, code: 'MG', name: 'Madagascar'},
        {country_pk: 131, code: 'MW', name: 'Malawi'},
        {country_pk: 132, code: 'MY', name: 'Malaysia'},
        {country_pk: 133, code: 'MV', name: 'Maldives'},
        {country_pk: 134, code: 'ML', name: 'Mali'},
        {country_pk: 135, code: 'MT', name: 'Malta'},
        {country_pk: 136, code: 'XM', name: 'Man (Isle of)'},
        {country_pk: 137, code: 'MH', name: 'Marshall Islands'},
        {country_pk: 138, code: 'MQ', name: 'Martinique'},
        {country_pk: 139, code: 'MR', name: 'Mauritania'},
        {country_pk: 140, code: 'MU', name: 'Mauritius'},
        {country_pk: 141, code: 'YT', name: 'Mayotte'},
        {country_pk: 142, code: 'MX', name: 'Mexico'},
        {country_pk: 143, code: 'FM', name: 'Micronesia'},
        {country_pk: 144, code: 'MD', name: 'Moldova'},
        {country_pk: 145, code: 'MC', name: 'Monaco'},
        {country_pk: 146, code: 'MN', name: 'Mongolia'},
        {country_pk: 147, code: 'MS', name: 'Montserrat'},
        {country_pk: 148, code: 'MA', name: 'Morocco'},
        {country_pk: 149, code: 'MZ', name: 'Mozambique'},
        {country_pk: 150, code: 'MM', name: 'Myanmar'},
        {country_pk: 151, code: 'NA', name: 'Namibia'},
        {country_pk: 152, code: 'NR', name: 'Nauru'},
        {country_pk: 153, code: 'NP', name: 'Nepal'},
        {country_pk: 154, code: 'AN', name: 'Netherlands Antilles'},
        {country_pk: 155, code: 'NL', name: 'Netherlands The'},
        {country_pk: 156, code: 'NC', name: 'New Caledonia'},
        {country_pk: 157, code: 'NZ', name: 'New Zealand'},
        {country_pk: 158, code: 'NI', name: 'Nicaragua'},
        {country_pk: 159, code: 'NE', name: 'Niger'},
        {country_pk: 160, code: 'NG', name: 'Nigeria'},
        {country_pk: 161, code: 'NU', name: 'Niue'},
        {country_pk: 162, code: 'NF', name: 'Norfolk Island'},
        {country_pk: 163, code: 'MP', name: 'Northern Mariana Islands'},
        {country_pk: 164, code: 'NO', name: 'Norway'},
        {country_pk: 165, code: 'OM', name: 'Oman'},
        {country_pk: 166, code: 'PK', name: 'Pakistan'},
        {country_pk: 167, code: 'PW', name: 'Palau'},
        {country_pk: 168, code: 'PS', name: 'Palestinian Territory Occupied'},
        {country_pk: 169, code: 'PA', name: 'Panama'},
        {country_pk: 170, code: 'PG', name: 'Papua new Guinea'},
        {country_pk: 171, code: 'PY', name: 'Paraguay'},
        {country_pk: 172, code: 'PE', name: 'Peru'},
        {country_pk: 173, code: 'PH', name: 'Philippines'},
        {country_pk: 174, code: 'PN', name: 'Pitcairn Island'},
        {country_pk: 175, code: 'PL', name: 'Poland'},
        {country_pk: 176, code: 'PT', name: 'Portugal'},
        {country_pk: 177, code: 'PR', name: 'Puerto Rico'},
        {country_pk: 178, code: 'QA', name: 'Qatar'},
        {country_pk: 179, code: 'RE', name: 'Reunion'},
        {country_pk: 180, code: 'RO', name: 'Romania'},
        {country_pk: 181, code: 'RU', name: 'Russia'},
        {country_pk: 182, code: 'RW', name: 'Rwanda'},
        {country_pk: 183, code: 'SH', name: 'Saint Helena'},
        {country_pk: 184, code: 'KN', name: 'Saint Kitts And Nevis'},
        {country_pk: 185, code: 'LC', name: 'Saint Lucia'},
        {country_pk: 186, code: 'PM', name: 'Saint Pierre and Miquelon'},
        {country_pk: 187, code: 'VC', name: 'Saint Vincent And The Grenadines'},
        {country_pk: 188, code: 'WS', name: 'Samoa'},
        {country_pk: 189, code: 'SM', name: 'San Marino'},
        {country_pk: 190, code: 'ST', name: 'Sao Tome and Principe'},
        {country_pk: 191, code: 'SA', name: 'Saudi Arabia'},
        {country_pk: 192, code: 'SN', name: 'Senegal'},
        {country_pk: 193, code: 'RS', name: 'Serbia'},
        {country_pk: 194, code: 'SC', name: 'Seychelles'},
        {country_pk: 195, code: 'SL', name: 'Sierra Leone'},
        {country_pk: 196, code: 'SG', name: 'Singapore'},
        {country_pk: 197, code: 'SK', name: 'Slovakia'},
        {country_pk: 198, code: 'SI', name: 'Slovenia'},
        {country_pk: 199, code: 'XG', name: 'Smaller Territories of the UK'},
        {country_pk: 200, code: 'SB', name: 'Solomon Islands'},
        {country_pk: 201, code: 'SO', name: 'Somalia'},
        {country_pk: 202, code: 'ZA', name: 'South Africa'},
        {country_pk: 203, code: 'GS', name: 'South Georgia'},
        {country_pk: 204, code: 'SS', name: 'South Sudan'},
        {country_pk: 205, code: 'ES', name: 'Spain'},
        {country_pk: 206, code: 'LK', name: 'Sri Lanka'},
        {country_pk: 207, code: 'SD', name: 'Sudan'},
        {country_pk: 208, code: 'SR', name: 'Suriname'},
        {country_pk: 209, code: 'SJ', name: 'Svalbard And Jan Mayen Islands'},
        {country_pk: 210, code: 'SZ', name: 'Swaziland'},
        {country_pk: 211, code: 'SE', name: 'Sweden'},
        {country_pk: 212, code: 'CH', name: 'Switzerland'},
        {country_pk: 213, code: 'SY', name: 'Syria'},
        {country_pk: 214, code: 'TW', name: 'Taiwan'},
        {country_pk: 215, code: 'TJ', name: 'Tajikistan'},
        {country_pk: 216, code: 'TZ', name: 'Tanzania'},
        {country_pk: 217, code: 'TH', name: 'Thailand'},
        {country_pk: 218, code: 'TG', name: 'Togo'},
        {country_pk: 219, code: 'TK', name: 'Tokelau'},
        {country_pk: 220, code: 'TO', name: 'Tonga'},
        {country_pk: 221, code: 'TT', name: 'Trinidad And Tobago'},
        {country_pk: 222, code: 'TN', name: 'Tunisia'},
        {country_pk: 223, code: 'TR', name: 'Turkey'},
        {country_pk: 224, code: 'TM', name: 'Turkmenistan'},
        {country_pk: 225, code: 'TC', name: 'Turks And Caicos Islands'},
        {country_pk: 226, code: 'TV', name: 'Tuvalu'},
        {country_pk: 227, code: 'UG', name: 'Uganda'},
        {country_pk: 228, code: 'UA', name: 'Ukraine'},
        {country_pk: 229, code: 'AE', name: 'United Arab Emirates'},
        {country_pk: 230, code: 'GB', name: 'United Kingdom'},
        {country_pk: 231, code: 'US', name: 'United States'},
        {country_pk: 232, code: 'UM', name: 'United States Minor Outlying Islands'},
        {country_pk: 233, code: 'UY', name: 'Uruguay'},
        {country_pk: 234, code: 'UZ', name: 'Uzbekistan'},
        {country_pk: 235, code: 'VU', name: 'Vanuatu'},
        {country_pk: 236, code: 'VA', name: 'Vatican City State (Holy See)'},
        {country_pk: 237, code: 'VE', name: 'Venezuela'},
        {country_pk: 238, code: 'VN', name: 'Vietnam'},
        {country_pk: 239, code: 'VG', name: 'Virgin Islands (British)'},
        {country_pk: 240, code: 'VI', name: 'Virgin Islands (US)'},
        {country_pk: 241, code: 'WF', name: 'Wallis And Futuna Islands'},
        {country_pk: 242, code: 'EH', name: 'Western Sahara'},
        {country_pk: 243, code: 'YE', name: 'Yemen'},
        {country_pk: 245, code: 'ZM', name: 'Zambia'},
        {country_pk: 246, code: 'ZW', name: 'Zimbabwe'},
        {country_pk: 247, code: 'XK', name: 'Kosovo'},
        {country_pk: 248, code: 'ME', name: 'Montenegro'}
    ]
}